### ISSUE TITLE
Creating new studies in deposition app and retaining old GCST

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#505] opened 2021-10-21 18:33 UTC
We have some old studies where many GWAS (associations and/or sumstats) were entered under a single GCST, due to the limitations of the old curation system. Examples are Suhre PMID 28240269 (1124 protein measurement GWAS) Shin PMID 24816252 (1000 metabolite GWAS). More examples here: https://docs.google.com/spreadsheets/d/1pLA2uTsO3I_1lgvNMcI1IlEHo8Ms_-QxN-z9RZNMp1g/edit#gid=641348915

These now need splitting out correctly so that each GWAS has its own GCST. They were curated under the old curation system so cannot be edited using DepoCuration.

One easy solution would be to delete the publication from the curation db, add it again and create a new submission for the PMID. However, it is bad practise to allow accession IDs to be removed from a resource. We need a solution to create the new studies (via the deposition app) whilst retaining or re-using the original GCST.

**Comment by ljwh2** [comment] 2021-10-21 18:36
@sajo-ebi please propose a solution

**Comment by ljwh2** [comment] 2021-11-24 14:46
@sajo-ebi You suggested we could manually update the GCSTs in the database. Therefore the workflow would be: 
1. Curator unpublishes study in curation app.
2. Curator deletes publication from curation app.
3. Curator adds publication to curation app again
4. Curator creates submission for publication, imports and curates
5. Developer manually updates one of the GCSTs to the old one. 

Or, is there any way to open the publication for sumstats & metadata submission without deleting it?

**Comment by sajo-ebi** [comment] 2021-11-25 16:32
@ljwh2 Have updated both the publications '28240269' &  '24816252' so that they are open for submission, No need to delete the PubmedId in curation app. Curators should should create the submission in Deposition UI  & update me so that I can reinstate the old GCST Ids , Please keep in mind not to import the submission without me manually changing the GCST Ids.

**Comment by buniello** [comment] 2021-11-30 10:19
Hi @sajo-ebi, the PMIDs in the comment above are still "CLOSED" for submission. Is that expected behavior?

**Comment by sajo-ebi** [comment] 2021-11-30 11:00
HI @buniello the PMId got updated when Deposition Sync ran , can you try now to create submission

**Comment by buniello** [comment] 2021-11-30 11:42
They are both open for submission now, thanks @sajo-ebi

**Comment by buniello** [comment] 2021-12-03 10:25
@ljwh2, I have now submitted the ticket for the creation of Suhre EFO terms (750 terms): https://github.com/EBISPOT/efo/issues/1369. 
Once these terms are created, I will be able to start testing this task. Hopefully soon.

**Comment by buniello** [comment] 2022-02-02 10:00
yes, I have the EFOs for Suhre - they are awaiting to be loaded into the curation database @ljwh2

**Comment by buniello** [comment] 2022-03-07 10:12
Please see this ticket for the list of publication to split: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/496

**Comment by sajo-ebi** [comment] 2022-03-10 12:42
Hi @buniello unfortunately Deposition Sync always makes it closed when it run as the studies were published before , Have opened the '28240269' & '24816252', you can create submission today , I can change GCSTId once you have created submission

**Comment by buniello** [comment] 2022-03-10 15:09
Thank you @sajo-ebi, I have created the two submissions today.
PMID 28240269 is https://www.ebi.ac.uk/gwas/studies/GCST004365 at the moment
PMID 24816252 is https://www.ebi.ac.uk/gwas/studies/GCST002443 at the moment

**Comment by sajo-ebi** [comment] 2022-03-10 15:48
@buniello can you let me know the submission Ids ?

**Comment by buniello** [comment] 2022-03-21 16:43
Hi @sajo-ebi, it does not matter which study adopts the original  GCST004365. For simplicity, let's assign it to the first study on the list?

**Comment by ljwh2** [comment] 2022-03-23 10:25
closing this ticket, please create new ones for other studies @buniello

**Comment by buniello** [comment] 2022-04-05 09:48
Hi @sajo-ebi, I have re-opened this issue because none of the GCSTs assigned to the new submission for suhre match with the current GCST in the Catalog: https://www.ebi.ac.uk/gwas/publications/28240269. 
The current GCST in Catalog for Suhre is GCST004365. The newly assigned GCSTs are downloadable from here: https://www.ebi.ac.uk/gwas/deposition/submission/622a122378a7f500016a5342.
Also tagging @ljwh2 as she can follow this up while I am on leave.

**Comment by buniello** [comment] 2022-04-06 13:18
Thank you @sajo-ebi!

**Closed** 2022-04-06 13:19 UTC
