### ISSUE TITLE
Publication management page: column sort

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1335] opened 2024-05-29 12:27 UTC
In the sandbox [Publication management page](https://wwwdev.ebi.ac.uk/gwas/depo-curation/publications), sort by first author and publication date does not work. Sometimes it works on first click, but then no results are shown and the page becomes non responsive. @sajo please fix

**Comment by ala-ebi** [comment] 2024-06-04 13:42
caused by PMIDs assigned to more than one BoW (sandbox data), pushed a fix to get only one

**Closed** 2024-07-24 09:42 UTC
