### ISSUE TITLE
Background EFO does not automatically apply to associations on import

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#529] opened 2021-11-23 09:07 UTC
Example submission template with main EFO and background EFO: 

[https://app.zenhub.com/files/2995118/043bbb3a-cffa-4ad7-af2c-a91c9dbda048/download](https://app.zenhub.com/files/2995118/043bbb3a-cffa-4ad7-af2c-a91c9dbda048/download)

On import, the background trait showed correctly at study level:

![Screenshot 2021-11-23 at 09.06.43.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/1484812b-a85a-4266-8032-30f50e1c7308)

but for the associations, only the main EFO had been applied. 

Both main and background EFO should be applied to associations on import.

**Comment by ljwh2** [comment] 2022-01-11 17:17
closing as duplicate of goci#567

**Closed by ljwh2** 2022-01-11 17:17 UTC
