### ISSUE TITLE
Provide submitters with a list of GCSTs generated for their submission

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#72] opened 2020-05-13 15:23 UTC
After making a submission, submitters should be able to view a list of the GCSTs created for each study in their submission. The list should contain enough information for the submitter to tell which study goes with each GCST, e.g. Study tag, Trait.

**Comment by eks-ebi** [comment] 2020-05-13 15:23
This requirement comes from a comment and discussion in this document:
https://docs.google.com/document/d/16N69sYyLgF6Q3LUwKbGRqmWcG_JPMmMXWEybO9Df71Q/edit

Discussion below:

**Display the GCSTs on the “Submission Details” page**
Trish Whetzel
08:59 11 May
Resolve
+jalm@ebi.ac.uk this is the proposal on where and how to display GCSTs. Do you agree?
Jacqueline MacArthur
Jacqueline MacArthur
13:50 11 May
This sounds good. But how do submitters go back and review GCSTs for a submission after they've clicked "Submit"? I now can't see my submission under "My submissions". Yes, this data should be downloadable.
Jacqueline MacArthur
Jacqueline MacArthur
15:11 11 May
I've now found my submission - problem was that you can't search by GCP, so very difficult to find a submission without a PubMed ID. +twhetzel@ebi.ac.uk - could we add ability to search by GCP to my submissions page?
Trish Whetzel
Trish Whetzel
15:27 11 May
Good point, I'll look into whether that data can also be searched by a GCPID
Jacqueline MacArthur
Jacqueline MacArthur
16:24 11 May
It would be useful for submitters to also receive this in an email, however not essential if they can find submission by GCP and then download
Trish Whetzel
Trish Whetzel
16:48 11 May
Can you let Tudor know of any changes for email content?
Jacqueline MacArthur
Jacqueline MacArthur
18:08 11 May
This isn't essential as long as submitters can download
Trish Whetzel
Trish Whetzel
08:13 Yesterday
Can we talk more about this at the 1:00 Tuesday meeting? One question is, since the GCSTs will be in this L2 download template file that is currently being worked on, is this sufficient as a download file with GCTs for the submitter to have a record of these or would a separate download file with only GCST, study tag, reported trait, and FTP link be needed?
Show less

**Comment by eks-ebi** [comment] 2020-05-13 15:25
Assigning to Tudor, as requested on Slack. Also assigning to Jackie, because I think she made the initial request in the Google doc, and might have a clearer idea of what is required.

**Comment by eks-ebi** [comment] 2020-05-13 15:26
Example GCST download file:
[gcst_list.xlsx](https://github.com/EBISPOT/goci/files/4622938/gcst_list.xlsx)

**Comment by eks-ebi** [comment] 2020-05-13 15:27
The above file relates to this submission: http://193.62.54.159/gwas/deposition/submission/5ea74f5ef024f2000185b55c

**Comment by JalMacArthur** [comment] 2020-05-13 15:57
Hi. I reviewed file. From file it looks like there is no requirement for study tag to be unique. Therefore you can’t tell which study the GCST relates to - e.g. row 5 and row 22 are identical.

I think there needs to be requirement for a study tag within submission to be unique for that submission if these are going to be used to identify study.

I think you need the SS file related to each study too.

**Comment by eks-ebi** [comment] 2020-05-14 08:31
One other minor comment about the file: assuming this is only for reading and not for users to enter any new information, some of the elements copied over from the template could be confusing:

I suggest:
* Remove the the grey/orange colouring (optional/mandatory) of the column headers - it doesn't mean anything if you are not entering info
* Remove "Add your data below this line"

**Comment by tudorgroza** [comment] 2020-05-14 08:54
@JalMacArthur - the file is supposed to be just a reproduction of what was included with the original submission. If there are requirements for uniqueness on fields, etc - these should be done at the validation step.
(As a side note here - not sure we're actually enforcing study tags to be unique per row ... I know they should be, but I don't think we're enforcing it)

I can include the SS file

@eks-ebi - I'm reusing the template service to produce this file. I'll have a go at meeting your requirements - but cannot promise, since I don't want to mess up the current functionality. If I can't do it there, I can produce a similar Excel file, but won't be that pretty :)

**Comment by eks-ebi** [comment] 2020-05-14 10:24
@tudorgroza OK, I can see that the format might be tricky to change then. In that case, I would say my suggestions are not essential

**Comment by tudorgroza** [comment] 2020-05-14 10:33
@eks-ebi - Is this acceptable?
[gcst_list.xlsx](https://github.com/EBISPOT/goci/files/4627671/gcst_list.xlsx)

**Comment by JalMacArthur** [comment] 2020-05-14 10:57
Is it possible to also add the summary statistics filename and ftp url?

**Comment by tudorgroza** [comment] 2020-05-14 11:01
At this point, I can only add the data provided in the original file. I can add the SS file name if provided - but not the FTP url.

**Comment by JalMacArthur** [comment] 2020-05-14 11:44
Could you add the filename, this will be in the file submitted.

**Comment by tudorgroza** [comment] 2020-05-15 04:57
Done. Please see here (this example is perhaps not the best). The backend functionality is already deployed in Sandbox, so as soon as the UI is ready you will be able to test it there.

[gcst_list.xlsx](https://github.com/EBISPOT/goci/files/4632294/gcst_list.xlsx)

**Comment by twhetzel** [comment] 2020-06-04 16:44
Released to PROD

**Closed by twhetzel** 2020-06-04 16:44 UTC
Labels: Priority: High, Type: Enhancement
