### ISSUE TITLE
Import Submission Changes to include new Reported Traits & EFO Traits

### ISSUE THREAD

**Issue by sajo-ebi** [EBISPOT/goci#631] opened 2022-02-22 17:01 UTC
Once the Disease Traits & EFO Traits have been implemented in Depo Curation , they will be used to map traits to studies & import submission need to be changed in order to read data from the new database objects instead of previously used free text. This will need changes in Ingest Service & Goci codebase

**Comment by sajo-ebi** [comment] 2022-02-23 10:59
To make the Mongo DB compatible with Oracle DB we need to make some changes in the data model design for Reported Traits & EFO Traits

**Comment by sajo-ebi** [comment] 2022-03-01 17:44
@eks-ebi The changes to sync the Disease/EFO Traits from Depo Curation to Curation is complete now.

The Sync process will run every hour once so any changes you do in Traits in Depo Curation should be reflected with in an hour.

For the submission we have a new flow where the traits will be mapped using the Study Traits Bulk upload mapping for both Disease & EFO Traits & then the import of submission should happen.

Please validate the import submission in particular whether Trait changes done in Depo Curation are reflecting in Curation Import

**Comment by eks-ebi** [comment] 2022-03-08 12:01
I can confirm that Reported traits added in Depo-curation appear later in the Curation database.

**Comment by eks-ebi** [comment] 2022-03-08 12:04
@sajo-ebi I haven't yet been able to test whether the Study Traits Bulk upload mapping is carried over to curation, because I am having errors with the bulk upload itself:

Tried assigning a reported trait to study GCST90000225 in this submission using bulk upload: https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/5fa160ccf59a3b00016dedaf

Upload successful according to report:
`accession	trait	uploadComment	links
GCST90000225	Asthma1	"Study for accession GCST90000225 successfully Updated with trait : Asthma1"	[]
`
But the new reported trait doesn't appear on the submission page: https://wwwdev.ebi.ac.uk/gwas/depo-curation/submissions/5fa160ccf59a3b00016dedaf

**Comment by ljwh2** [comment] 2022-03-14 10:33
Just documenting here that Elliot and I discussed and think the **study tag** should be included in the Study Traits Bulk upload mapping. This would allow curators to make an intuitive link between the GCSTs and traits, and prevent mistakes occurring. Ideally, the upload should be rejected if study tags and GCSTs do not match. If this is complicated to add, it is not necessarily a blocker to the first release.
@eks-ebi please confirm

**Comment by eks-ebi** [comment] 2022-03-14 11:19
Thanks @ljwh2, one clarification I would make is that we would like the **study tag** to be included in both the Reported Trait and EFO Trait Bulk Upload files.

Also, at the moment, when a curator goes into the study page for a submission and downloads the bulk upload .tsv template, its contents are generic and always contain the same dummy examples of both traits and GCSTs:
a) eventually, it would be more useful if the template was auto-populated with the actual GCSTs for the submission the curator is editing (and any existing traits already included in the submitted excel file)
b) the dummy examples seem to be real trait labels and GCSTs - could this be dangerous and allow for incorrect traits to be assigned, if e.g. a curator forgets to delete one of the examples. So in the shorter term, maybe it would be better to remove the example rows, or replace them with examples that are clearly not real traits/GCSTs (e.g. "Example trait" | "GCSTxxxxxxxx")

**Comment by sajo-ebi** [comment] 2022-03-14 12:48
@eks-ebi the first point we can address that at later point of time.
we can implement the 2nd point with out much efforts will push the fix & let you know

**Comment by eks-ebi** [comment] 2022-03-15 16:27
confirmed! thanks @sajo-ebi

**Comment by sajo-ebi** [comment] 2022-03-21 17:27
@eks-ebi Thanks for the elaborate testing , on point 3 & 4 , they are quick fixes I can put them out by tomorrow , On Point 5 just wanted to clarify we haven't done anything to map association to traits , they are still using the old free text Traits in template not the ones added through Trait mapping , clarifying to avoid any confusion or wrong assumption

**Comment by eks-ebi** [comment] 2022-03-21 17:39
@sajo-ebi Thanks for that very important clarification, I had made a wrong assumption there.
I think it will be problematic for studies and associations to get their trait mappings from different sources, so we will probably need to update the association mappings so that the the traits assigned to studies are also propagated to all of their associations. I'd suggest a quick discussion at the next sprint meeting and if everyone agrees, I can create a ticket for it.

**Comment by sajo-ebi** [comment] 2022-03-22 09:50
@eks-ebi I can investigate to find how much changes are needed for making association mapping to the new traits functionality , I assume it shouldn't be huge amount of changes , if it is small I can push the same to the Dev environment & ask you to validate

**Comment by eks-ebi** [comment] 2022-03-22 09:53
Great, let me know when you need my input!

**Comment by sajo-ebi** [comment] 2022-03-22 17:32
@eks-ebi Resolved point 3 (Study Tags) in studies list & deployed in Sandbox . For point 4 unfortunately the table is dynamic & we don't have control over the order of columns that appear in sample template , but you can manually change the column names & make it same as the study accession sheet , just ensure the columns names are exactly same as given in the template.

On the Association mapping to traits it is working fine without any intervention , the existing code seems to pick the traits mapped to study & assigns it to association so we are good from that perspective

**Comment by eks-ebi** [comment] 2022-03-23 10:43
@sajo-ebi We discussed today that some traits appear with surrounded by " after importing them into Curation - can you please check that before releasing?

**Closed** 2022-04-06 10:23 UTC
