### ISSUE TITLE
GCP000405 summary statistics not showing on FTP

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/goci#827] opened 2022-08-16 10:33 UTC
We had a user submission on Friday 12th August '62f1496415ccca0001f022c6' with an embargo date set to date of publication.
They then e-mailed to ask for the embargo to be removed, which I did using the remove embargo script, again on Friday, 

I believe the files should now be showing on the FTP but the parent directory is not even visible here: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/
One of the GCSTs: GCST90132242
Full list of GCSTs:
[https://app.zenhub.com/files/2995118/4720fca4-b367-4a89-9b23-48f3446cf611/download](https://app.zenhub.com/files/2995118/4720fca4-b367-4a89-9b23-48f3446cf611/download)
If I search the sumstats release report e-mail it looks like the GCST is unexpected on staging.
Please investigate and release these sumstats.

**Comment by jdhayhurst** [comment] 2022-08-17 08:40
The files are on staging but the studies are not in the database. This suggests that the depo sync failed to run

**Comment by sprintell** [comment] 2022-08-24 09:16
This can only be fixed by looking into the deposition sync. @sajo-ebi

**Comment by ala-ebi** [comment] 2022-08-30 13:14
We found the cause for this, it's the fact that the submission has the new "DEPOSITION_COMPLETE" status but the deposition-sync only picks up submissions that have the "SUBMITTED" status.

I have manually changed the status for this submission and rerun the deposition-sync, I can see it in the Oracle DB now but we need a DR to get to the public facing site.

To fix the problem for future submissions we need to either change the deposition-sync to sync unpublished submissions with "DEPOSITION_COMPLETE", or by changing the default status of BoW unpublished submissions to "SUBMITTED" instead of "DEPOSITION_COMPLETE".

I would guess there are other unpublished BoW submissions that still have "DEPOSITION_COMPLETE" and are not synced to the oracle side, we have to manually take care of those by changing their status to "SUBMITTED".

@earlEBI please let me know how urgent getting this submission to the public site is, if it can wait for Wednesday next week (DR date) or not.
Also we need a ticket for the general software fix, and the manual fix to the corrupt submissions (BoW + "DEPOSITION_COMPLETE").

**Comment by earlEBI** [comment] 2022-08-30 13:28
@ala-ebi thanks. I think as long as the FTP link works, inclusion on the site can wait until next DR. 

I think this submission may also be affected as I released embargo today and told them their data would be available on FTP tomorrow - could you please check? https://www.ebi.ac.uk/gwas/deposition/submission/6304d7b115ccca0001f1101b

**Comment by earlEBI** [comment] 2022-08-30 13:36
@ala-ebi can I tell the user the FTP link should work tomorrow? (http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90133001-GCST90134000)

**Comment by earlEBI** [comment] 2022-08-31 08:08
FTP links are working now, thanks

**Comment by earlEBI** [comment] 2022-09-01 08:13
@ala-ebi Hi Ala, this user seems very keen to see their sumstats available on the FTP asap - would you be able to change their status as above so their data is released overnight? submission id '6304d7b115ccca0001f1101b'?

**Comment by sprintell** [comment] 2022-09-07 09:39
waiting for DR to be sure its showin gin the public facing

**Comment by ljwh2** [comment] 2022-09-21 09:20
Sumstats now available and indexed in UI

**Closed** 2022-09-21 09:31 UTC
