### ISSUE TITLE
Slurm Cluster Migration for Python Infrastructure

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/goci#1179] opened 2023-10-26 10:35 UTC
- [ ] gwas-sumstats-harmoniser
- [x] Summary statistics with HDF5
- [x] Summary Statistics File Validator
- [x] gwas-sumstats-tools
- [x] sum-stats-formatter

- [x] eQTL-SumStats
- [x] gwas-template-services
- [x] gwas-sumstats-service

- [x] gwas-utils
- [x] gwas-curation-utils
- [x] gwas-ebi-search-index
- [x] gwas-solr-slim

**Comment by sprintell** [comment] 2023-11-01 11:34
@karatugo should have a session with @jdhayhurst before commencing this

**Comment by ljwh2** [comment] 2023-11-15 11:25
Do harmoniser last so Yue can have time to complete her work

**Comment by karatugo** [comment] 2023-11-21 08:27
| Repo                   | PR      |  Status         |
| ---------------- | ----------- | ----------- |
| gwas-sumstats-harmoniser | | |
| Summary statistics with HDF5 | | |
| Summary Statistics File Validator | | |
| gwas-sumstats-tools | | |
| sum-stats-formatter | | |
| eQTL-SumStats | | |
| gwas-template-services | | |
| gwas-sumstats-service | https://github.com/EBISPOT/gwas-sumstats-service/pull/273 | [Test in dev](https://gitlab.ebi.ac.uk/gwas/gwas-sumstats-service/-/jobs/1479108) failed |
| gwas-utils | https://github.com/EBISPOT/gwas-utils/pull/158 | LSF is not used anymore, cleaned up the old LSF code |
| gwas-curation-utils | No LSF usage was found | |
| gwas-ebi-search-index | No LSF usage was found | |
| gwas-solr-slim   | https://github.com/EBISPOT/gwas-solr-slim/pull/52   | Test OK in dev, waiting for review |

**Comment by karatugo** [comment] 2024-01-15 16:14
All done. Releases needed for the migration to SLURM.

**Comment by sprintell** [comment] 2024-02-21 10:40
This wil be released wiht metadata Yaml Update Feature

**Comment by ljwh2** [comment] 2024-03-06 10:42
Error in SLURM - waiting for input from TSC

**Comment by karatugo** [comment] 2024-03-18 17:12
Released https://github.com/EBISPOT/gwas-sumstats-harmoniser/releases/tag/v1.0.5 and https://github.com/EBISPOT/gwas-sumstats-harmoniser/releases/tag/v1.1.4

**Comment by karatugo** [comment] 2024-03-18 18:03
- [ ] Enable `scrontab` entries for harmoniser migration before deployment

**Comment by karatugo** [comment] 2024-03-19 14:16
For gwas-sumstats-harmoniser migration:

Test submitted to codon-slurm but failed. @jiyue1214 is helping me to investigate the problem.

**Comment by karatugo** [comment] 2024-03-19 16:22
Released https://github.com/EBISPOT/gwas-sumstats-harmoniser/releases/tag/v1.1.5 and https://github.com/EBISPOT/gwas-sumstats-harmoniser/releases/tag/v1.0.6 and submitted the test files to codon-slurm again.

**Comment by karatugo** [comment] 2024-03-20 13:35
For gwas-sumstats-harmoniser migration:

Test submitted to codon-slurm and it's successful. There's one small mistake in meta.yaml files. @jiyue1214 is helping me to investigate the problem.

**Comment by karatugo** [comment] 2024-03-28 12:07
For gwas-sumstats-harmoniser migration:

I compared the output of the harmonisation pipeline in SLURM and LSF.

- `.h.tsv.gz`, `.h.tsv.gz.tbi`, `md5sum.txt` files are identical. 
- In running.log, we have a higher percentage of sites that carried forward. 
- In meta yaml, @jiyue1214  fixed a few bugs (coordinate system and samples). (thanks @jiyue1214 !)

I suggest we deploy this after the Easter long weekend. I'll coordinate it with Yue.

**Comment by jiyue1214** [comment] 2024-04-18 21:39
Issue:
In running.log, we have a higher percentage of sites that are carried forward.

Primary investigation:
`Percentage of sites that are carried forward = Carried forward variants / ( Carried forward variants + Unmapped variants). `
Based on the log file, the number of sites that are carried forward are same, which means the difference is caused by the unmapped variants. To investigate the reason why unmapped variants are different, I need to rerun the pipeline and use intermediate files to help.

**Comment by jiyue1214** [comment] 2024-04-30 21:23
I rerun the pipeline with the intermediate files and found:
1. Their intermediate files are the same (md5sum of two unmapped files are identical)
2. I can repeat the slight difference between the LSF and Slurm, but the **Slurm result is the correct** number.
3. In the LSF, nextflow read the GCST90293086's unmapped file to GCST90293085 log work folder. However, in the Slurm, it is it was the correct one.

This is not supported by the code difference. However, to double-check it, yue can change the LSF code to slurm (only change the executor.)

**Comment by jiyue1214** [comment] 2024-05-01 09:55
I confirm the Slurm result is correct. We can close this ticket.  For the reason causing the problem on LSF (the Harmonisation result is correct, only the unmapped file did not match the GCST), I will generate another ticket to look into more details.

**Comment by ljwh2** [comment] 2024-05-01 10:20
@karatugo to release

**Comment by ljwh2** [comment] 2024-05-22 09:20
@jiyue1214  added additional feature, waiting for Yue before releasing

**Comment by jiyue1214** [comment] 2024-06-05 09:02
1. All scripts are ready and will start to run today via crontab
2. A small action is that I will active scrontab instead of crontab based on the [ITSC info](https://embl.service-now.com/esc?id=kb_article&table=kb_knowledge&sysparm_article=KB0010982)

**Comment by jiyue1214** [comment] 2024-06-11 20:46
Nextflow pipeline is running on Slurm and can be monitored by the nextflow tower daily. 
Question: @karatugo, According to the scrontab, we have not activated the refresh harmonisation queue, queue GWAS-SSF files for harmonisation, and queue pre-GWAS-SSF files for harmonisation. Should we activate them as well?

**Comment by jiyue1214** [comment] 2024-06-12 08:33
We have migrated all crontab jobs to Slurm this morning. This ticket can be moved to Done. 
Just need to double-check if they are running successfully tomorrow.

**Comment by sprintell** [comment] 2024-06-19 10:29
been release at the moment, ticket due to be closed at end of sprint

**Closed** 2024-06-26 09:42 UTC
Labels: Maintenance & Tech. Debts
