### ISSUE TITLE
Investigate problems with EFO term "treatment"

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/goci#647] opened 2022-03-16 09:38 UTC
This EFO term is not displaying correctly in the GWAS Catalog downloads, however there doesn't seem to be any obvious cause for the problem in this case:

label: treatment
URI: http://www.ebi.ac.uk/efo/EFO_0000727
short form: EFO_0000727

Initial observations:
* The term label, URI and short form in the GWAS Catalog curation database all match those in OLS
* The term displays correctly in the Search UI
* The term does **not** display correctly in the download spreadsheets
* There are no duplicate terms with the same label, URI or short form in either the GWAS Catalog or OLS

**Comment by eks-ebi** [comment] 2022-03-16 09:51
For other missing terms in the download, specific problems were identified and resolved in prev ticket: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/613. But this term does not have any of the same issues as those other terms, so created this separate ticket to investigate.

**Comment by ala-ebi** [comment] 2022-07-20 14:55
identified the problem, a piece of code is excluding terms marked as "organizational_class" in EFO from being loaded into the app, "treatment" falls into this category and was excluded, the rest of the list includes
'anatomy basic component' organizational_class "true"^^xsd:string
'chromosomal aberration' organizational_class "true"^^xsd:string
CS57544 organizational_class "true"^^xsd:string
'epigenetic factor' organizational_class "true"^^xsd:string
'epigenetic status' organizational_class "true"^^xsd:string
'experimental factor' organizational_class "true"^^xsd:string
'external control ratio' organizational_class "true"^^xsd:string
function organizational_class "true"^^xsd:string
'gene knock out' organizational_class "true"^^xsd:string
'genetic modification' organizational_class "true"^^xsd:string
'gram per kilogram' organizational_class "true"^^xsd:string
'information entity' organizational_class "true"^^xsd:string
'material entity' organizational_class "true"^^xsd:string
'material property' organizational_class "true"^^xsd:string
picoliter organizational_class "true"^^xsd:string
process organizational_class "true"^^xsd:string
quality organizational_class "true"^^xsd:string
role organizational_class "true"^^xsd:string
site organizational_class "true"^^xsd:string
treatment organizational_class "true"^^xsd:string

We agreed to remove the exclusion and after the next Software Release for goci, the DR right after will fix the issue.

**Comment by sprintell** [comment] 2022-08-10 10:28
Can't be closed because of Bug in EFO Downloaded file reported by gwas monitor and otehr user.

**Comment by ala-ebi** [comment] 2022-08-24 09:18
need to run the Solr Indexed deployment plan, instead of Production Curation

**Comment by ala-ebi** [comment] 2022-09-14 09:20
confirmed after DR

**Closed** 2022-09-14 09:42 UTC
Labels: Type: Bug, Type: Task
